### ISSUE TITLE
Rename it?

### ISSUE THREAD

**Issue by dabrahams** [paulaltin/git-hires-merge#17]
Google git-subline-merge and you won't find this.  What about `git-hires-merge`?

**Comment by paulaltin** [comment]
Finally got around to doing this. Thanks for the suggestion @dabrahams.

Code changes are in 3ca805455562e63cce964fffe10097ce1dd174bb, I will now rename the repository in GitHub, which I think means that the project URL will change to https://github.com/paulaltin/git-hires-merge

**Comment by dabrahams** [comment]
W00t!

**Comment by dabrahams** [comment]
Now we just need to get its google ranking up :-)
